# Teste para verificar se o frontend está funcionando
Write-Host "Testando se o frontend está funcionando..."
Write-Host "1. Abra o frontend no navegador"
Write-Host "2. Vá para a página de Agentes"
Write-Host "3. Clique em 'Criar Agente'"
Write-Host "4. Preencha os dados:"
Write-Host "   - Nome: José"
Write-Host "   - Tipo: jos"
Write-Host "   - Ícone: 🤖"
Write-Host "   - Cor: bg-blue-500"
Write-Host "5. Clique em 'Criar'"
Write-Host ""
Write-Host "Agora deve aparecer: 'Agente José criado com sucesso! Workflow foi iniciado automaticamente.'"
Write-Host "Em vez do erro anterior."
