# Teste para verificar se o frontend não usa mais dados mockados
Write-Host "Teste do frontend sem dados mockados"
Write-Host ""
Write-Host "1. Abra o frontend no navegador"
Write-Host "2. Vá para a página de Agentes"
Write-Host "3. Abra o console do navegador (F12)"
Write-Host "4. Recarregue a página (F5)"
Write-Host ""
Write-Host "Agora deve aparecer:"
Write-Host "- 'Resposta vazia ou formato não reconhecido, lista vazia'"
Write-Host "- 'Nenhum agente encontrado'"
Write-Host "- Lista vazia (sem dados mockados)"
Write-Host ""
Write-Host "Em vez de:"
Write-Host "- 'Resposta não tem formato esperado, usando dados mockados'"
Write-Host "- 'Usando agentes mockados'"
Write-Host "- Dados fake de agentes"
