# Teste do refresh automático com debug
Write-Host "Teste do refresh automático com debug"
Write-Host ""
Write-Host "1. Abra o frontend no navegador"
Write-Host "2. Vá para a página de Agentes"
Write-Host "3. Abra o console do navegador (F12)"
Write-Host "4. Clique em 'Criar Agente Automaticamente'"
Write-Host "5. Preencha os dados:"
Write-Host "   - Nome: Teste Debug"
Write-Host "   - Descrição: Teste de debug do refresh"
Write-Host "   - Ícone: 🤖"
Write-Host "   - Cor: bg-blue-500"
Write-Host "6. Clique em 'Criar'"
Write-Host ""
Write-Host "No console deve aparecer:"
Write-Host "✅ 'Criando agente com clonagem automática:'"
Write-Host "✅ 'Resposta da clonagem:' com status 200"
Write-Host "✅ 'Agente Teste Debug criado com sucesso! Workflow foi processado.'"
Write-Host "✅ 'REFRESH: Chamando loadAgentes() após criação bem-sucedida'"
Write-Host "✅ 'REFRESH: Carregando agentes via webhook...'"
Write-Host "✅ 'REFRESH: Resposta completa do webhook:'"
Write-Host ""
Write-Host "Se aparecer tudo isso, o refresh está funcionando!"
Write-Host "Se o webhook list-agentes retornar vazio, é problema do n8n, não do frontend."
